# Generated by Django 5.1 on 2024-08-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('close', models.FloatField()),
            ],
            options={
                'db_table': 'daily_closing_price',
                'indexes': [models.Index(fields=['ticker', 'date'], name='daily_closi_ticker_2e0cb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceChangePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('change_period', models.CharField(max_length=20)),
                ('percentage_change', models.FloatField()),
            ],
            options={
                'db_table': 'price_change_percentage',
                'indexes': [models.Index(fields=['ticker', 'date', 'change_period'], name='price_chang_ticker_88b4ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'stocks',
                'indexes': [models.Index(fields=['ticker', 'date'], name='stocks_ticker_998705_idx')],
            },
        ),
        migrations.CreateModel(
            name='TodaysData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'todays_data',
                'indexes': [models.Index(fields=['ticker', 'date'], name='todays_data_ticker_d08ad8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopGainersLosers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('gainers_or_losers', models.CharField(max_length=10)),
                ('percentage_change', models.FloatField()),
            ],
            options={
                'db_table': 'top_gainers_losers',
                'indexes': [models.Index(fields=['ticker', 'date', 'gainers_or_losers'], name='top_gainers_ticker_b5f9f4_idx')],
            },
        ),
    ]
