# Generated by Django 5.1 on 2024-08-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricechangepercentage',
            name='name',
            field=models.CharField(default='Nishant', max_length=10),
        ),
    ]
