# Generated by Django 5.1 on 2024-08-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyclosingprice_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyclosingprice',
            name='open',
        ),
    ]
