# Generated by Django 5.1 on 2024-08-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_dailyclosingprice_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosingprice',
            name='open',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
