# Generated by Django 5.1 on 2024-08-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240810_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyclosingprice',
            name='open',
            field=models.FloatField(default=0.0),
        ),
    ]
