# Generated by Django 5.1 on 2024-08-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dailyclosingprice_open'),
    ]

    operations = [
    ]
