# Generated by Django 5.1 on 2024-08-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240810_1033'),
    ]

    operations = [
    ]
