# Generated by Django 5.1 on 2024-08-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240810_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyclosingprice',
            name='open',
        ),
    ]
