# Generated by Django 5.1 on 2024-08-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_stock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
