# Generated by Django 5.1 on 2024-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosingprice',
            name='open',
            field=models.FloatField(default=1.0),
        ),
    ]
