# Generated by Django 5.1 on 2024-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dailyclosingprice_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricechangepercentage',
            name='min_change',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='todaysdata',
            name='todays_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topgainerslosers',
            name='booster',
            field=models.CharField(default='NA', max_length=5),
        ),
    ]
