# Generated by Django 5.1 on 2024-08-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pricechangepercentage_min_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyclosingprice',
            name='open',
        ),
        migrations.RemoveField(
            model_name='pricechangepercentage',
            name='min_change',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='todaysdata',
            name='todays_sell',
        ),
        migrations.RemoveField(
            model_name='topgainerslosers',
            name='booster',
        ),
    ]
