replicaCount: 2

image:
  repository: nishantddubey/frontend-app       #nishantddubey/stock-frontend
  tag: "2d474568d944c10d50d51c2eb782a33bd93b0917"  #"3"

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30000

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

nodeSelector: {}
tolerations: []
affinity: {}
