apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}
    spec:
      containers:
        - name: django-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - name: migration-history
              mountPath: /app/api/migrations  # Mount to this path in the container
      volumes:
        - name: migration-history
          hostPath:
            path:  /home/sigmoid/Desktop/migration-backup # Replace this with your local path
            type: Directory
