apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-migrations-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size based on your needs
