apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "backend.name" . }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
