replicaCount: 1

image:
  repository: nishantddubey/stock-database
  tag: "1"
  pullPolicy: IfNotPresent  # Add this line to specify when the image should be pulled

service:
  type: ClusterIP
  port: 3306
  targetPort: 3306

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
