apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'stock_data'
        metrics_path: '/api/metrics'
        static_configs:
          - targets: ['192.168.49.2:30001']  # Update this to your Django backend service name

    rule_files:
      - '/etc/prometheus/alerts.yml'

    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - '192.168.49.2:31002'  # Service name in Kubernetes

  alerts.yml: |
    groups:
      - name: stock_alerts
        rules:
          - alert: PositivePriceChangeAlert
            expr: price_change_percentage{change_period="24_hours"} > 2
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Price change percentage for stock {{ $labels.stock }} is above 2%"
              description: "The price change percentage for stock {{ $labels.stock }} has been above 2% for more than 1 minute."

          - alert: NegativePriceChangeAlert
            expr: price_change_percentage{change_period="24_hours"} < -5
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Price change percentage for stock {{ $labels.stock }} is below -5%"
              description: "The price change percentage for stock {{ $labels.stock }} has been below -5% for more than 1 minute."
