apiVersion: v2
name: stock-app
description: A Helm chart for Stock Management Application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: database
    version: 0.1.0
    repository: "file://charts/database"
  - name: monitoring
    version: 0.1.0
    repository: "file://charts/monitoring"
