apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: {{ include "database.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "database.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
