apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: {{ include "database.name" . }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
