apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    app: {{ include "database.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: db
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
  selector:
    app: {{ include "database.name" . }}
