replicaCount: 2

image:
  repository: nishantddubey/backend-app
  tag: "ec388"

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30001

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

nodeSelector: {}
tolerations: []
affinity: {}
