apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'stock_data'
        metrics_path: '/api/metrics'
        static_configs:
          - targets: ['192.168.49.2:30001']

    rule_files:
      - '/etc/prometheus/alerts.yml'

    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - '192.168.49.2:31002'

  alerts.yml: |
    groups:
      - name: stock_alerts
        rules:
          - alert: PositivePriceChangeAlert
            expr: price_change_percentage{change_period="24_hours"} > 2
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Price change percentage for stock  is above 2%"
              description: "The price change percentage for stock  has been above 2% for more than 1 minute."

          - alert: NegativePriceChangeAlert
            expr: price_change_percentage{change_period="24_hours"} < -5
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Price change percentage for stock  is below -5%"
              description: "The price change percentage for stock  has been below -5% for more than 1 minute."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31000
  type: NodePort
