apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'dubeynishant643@gmail.com'
      smtp_auth_username: 'dubeynishant643@gmail.com'
      smtp_auth_password: 'cgxulkydngcqmghv'
      smtp_require_tls: true
    receivers:
      - name: 'email_notifications'
        email_configs:
          - to: 'nishantddubey4@gmail.com'
            send_resolved: true
    route:
      receiver: 'email_notifications'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'stock_data'
        metrics_path: '/api/metrics'
        static_configs:
          - targets: ['backend:8000']
    rule_files:
      - '/etc/prometheus/alerts.yml'
    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - 'alertmanager-service:9093'
  alerts.yml: |
    groups:
      - name: stock_alerts
        rules:
          - alert: PositivePriceChangeAlert
            expr: price_change_percentage{change_period="24_hours"} > 2
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Price change percentage for stock {{ .stock }} is above 2%"
              description: "The price change percentage for stock {{ .stock }} has been above 2% for more than 1 minute."
          - alert: NegativePriceChangeAlert
            expr: price_change_percentage{change_period="24_hours"} < -5
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Price change percentage for stock {{ .stock }} is below -5%"
              description: "The price change percentage for stock {{ .stock }} has been below -5% for more than 1 minute."
