name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'Frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'Frontend/**'
      - '.github/workflows/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Ensure it runs on your local self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        if: contains(github.event.head_commit.message, 'backend')
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/stock-backend:$GITHUB_SHA \
            -f backend/Dockerfile backend/ --push

      - name: Build and push frontend image
        if: contains(github.event.head_commit.message, 'Frontend')
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/stock-frontend:$GITHUB_SHA \
            -f Frontend/Dockerfile Frontend/ --push

      - name: Set up kubectl context
        run: |
          kubectl config use-context minikube

      - name: Deploy to Minikube with Helm
        run: |
          helm upgrade --install stock-app ./stock-app \
            --set backend.image.repository=${{ secrets.DOCKER_USERNAME }}/stock-backend \
            --set backend.image.tag=$GITHUB_SHA \
            --set frontend.image.repository=${{ secrets.DOCKER_USERNAME }}/stock-frontend \
            --set frontend.image.tag=$GITHUB_SHA
