name: CI Pipeline

on:
  push:
    branches:
      - deployment  # Specify the branch to monitor, e.g., 'main'

jobs:
  build-backend:
    runs-on: [self-hosted]  # Use the self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          cd backend
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:$SHORT_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:$SHORT_SHA

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.8.0'  # Specify the Helm version you need

      - name: Upgrade Helm chart for backend
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          helm upgrade stock-app /home/sigmoid/Desktop/stock-app/stock-monitoring-system/stock-app \
            --set backend.image.tag=$SHORT_SHA \

  build-frontend:
    runs-on: [self-hosted]  # Use the self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          cd Frontend
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:$SHORT_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:$SHORT_SHA

      - name: Upgrade Helm chart for frontend
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          helm upgrade stock-app /home/sigmoid/Desktop/stock-app/stock-monitoring-system/stock-app \
            --set frontend.image.tag=$SHORT_SHA \
