name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'stock-app/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker registry secrets
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push backend image
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'backend')
        run: |
          TAG=${GITHUB_SHA::8}
          docker buildx build --platform linux/amd64 --tag ${{ secrets.DOCKER_USERNAME }}/stock-backend:$TAG -f backend/Dockerfile backend/ --push
          echo "BACKEND_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push frontend image
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'frontend')
        run: |
          TAG=${GITHUB_SHA::8}
          docker buildx build --platform linux/amd64 --tag ${{ secrets.DOCKER_USERNAME }}/stock-frontend:$TAG -f frontend/Dockerfile frontend/ --push
          echo "FRONTEND_TAG=$TAG" >> $GITHUB_ENV

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0'

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Update Helm deployment
        run: |
          helm upgrade --install stock-app ./stock-app \
            --set backend.image.repository=${{ secrets.DOCKER_USERNAME }}/stock-backend \
            --set backend.image.tag=$BACKEND_TAG \
            --set frontend.image.repository=${{ secrets.DOCKER_USERNAME }}/stock-frontend \
            --set frontend.image.tag=$FRONTEND_TAG
        env:
          KUBECONFIG: /home/runner/.kube/config
