name: CI Pipeline

on:
  push:
    branches:
      - deployment  # Specify the branch to monitor, e.g., 'main'

jobs:
  build-and-deploy:
    runs-on: [self-hosted]  # Use the self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Detect changes
        id: changes
        run: |
          echo "Checking for changes..."
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          echo "backend_changed=false" >> $GITHUB_ENV
          echo "frontend_changed=false" >> $GITHUB_ENV
          echo "database_changed=false" >> $GITHUB_ENV
          if echo "$CHANGED_FILES" | grep -q '^backend/'; then
            echo "backend_changed=true" >> $GITHUB_ENV
          fi
          if echo "$CHANGED_FILES" | grep -q '^Frontend/'; then
            echo "frontend_changed=true" >> $GITHUB_ENV
          fi
          if echo "$CHANGED_FILES" | grep -q '^database/'; then
            echo "database_changed=true" >> $GITHUB_ENV
          fi

      - name: Build and push backend Docker image
        if: env.backend_changed == 'true'
        run: |
          cd backend
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:$SHORT_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:$SHORT_SHA

      - name: Retry Helm upgrade for backend
        if: env.backend_changed == 'true'
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          RETRIES=5
          COUNT=0
          until [ $COUNT -ge $RETRIES ]
          do
            helm upgrade stock-app /home/sigmoid/Desktop/stock-app/stock-monitoring-system/stock-app \
              --set backend.image.tag=$SHORT_SHA && break
            COUNT=$[$COUNT+1]
            echo "Retrying... ($COUNT/$RETRIES)"
            sleep 30
          done
          if [ $COUNT -eq $RETRIES ]; then
            echo "Helm upgrade failed after $RETRIES attempts"
            exit 1
          fi

      - name: Build and push frontend Docker image
        if: env.frontend_changed == 'true'
        run: |
          cd Frontend
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:$SHORT_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:$SHORT_SHA

      - name: Retry Helm upgrade for frontend
        if: env.frontend_changed == 'true'
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          RETRIES=5
          COUNT=0
          until [ $COUNT -ge $RETRIES ]
          do
            helm upgrade stock-app /home/sigmoid/Desktop/stock-app/stock-monitoring-system/stock-app \
              --set frontend.image.tag=$SHORT_SHA && break
            COUNT=$[$COUNT+1]
            echo "Retrying... ($COUNT/$RETRIES)"
            sleep 30
          done
          if [ $COUNT -eq $RETRIES ]; then
            echo "Helm upgrade failed after $RETRIES attempts"
            exit 1
          fi
