name: CI Pipeline

on:
  push:
    branches:
      - main  # Specify the branch to monitor, e.g., 'main'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          cd backend
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:$SHORT_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:$SHORT_SHA

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          cd Frontend
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:$SHORT_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:$SHORT_SHA
